### PR TITLE
Consolidation of Node port, extensive test cases and a better way to run tests in browser

### PR DESCRIPTION
**Pull request by rla**
This Pull Request adds the following changes:

 * Ports the pengines.js to directly run on Node and replaces current non-maintained codebase
   at <https://www.npmjs.com/package/pengines>. The codebase and examples were written
   in CoffeScript, not easily usable for someone familiar with CoffeScript. This was also pointed
   out in the mailing list.
 * Replaces current browser test cases with much more extensive tests that run on both browsers
   and Node. The test cases cover all options, callbacks and various failure modes.
 * Adds brief README.md put together by using documentation from <http://pengines.swi-prolog.org>.

The Node port simply replaces jQuery with najax at runtime when the environment is not browser. This keeps 100% backwards compatibility in browsers. The changes to pengines.js are quite trivial.

Tests in the browser are now run using the headless Chromium. The test cases are in the file `test_js/tests.js`. The change adds `package.json` file which is required for publishing the pengines package to NPM. This file also specifies the Chromium version and makes it possible to automatically install it with a single command.

The tests are still ran through `test_js.pl`. There is a small section on testing in the README file. All necessary dependencies are fixed down to patch version so it's unlikely that the current setup of tests will go bad itself with toolset updates.

I have agreed with the current pengines package owner on NPM to re-publish the package once the PR gets merged. The NPM package gets major semver upgrade so anyone using the old CoffeeScript one still have working code.

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Whow!  please give me some time to review ...  I'm working on too many threads concurrently right now ...

**Comment by JanWielemaker** [comment]
Thanks!  The change may be large, but was easy to grasp.   An official maintained npm would be great!

**Comment by JanWielemaker** [comment]
I created an account (janwielemaker).  I see Anne picked this up as well though.   Connect me as you see fit.

**Comment by rla** [comment]
I added both accounts. Before republishing, the version number (semver) in package.json should be increased.

**Comment by JanWielemaker** [comment]
Thanks.  Good to see a simple to install version coming from a single source.  Not much changes at this level, so I expect few updates.

**Comment by Anniepoo** [comment]
I made a swiprolog account to publish https://github.com/Anniepoo/node-red-pengines should we use janwielemaker or that. Jan, sent you credentials.

**Comment by rla** [comment]
All owners have the same power so you can add others too. I'm not sure if Jan wants to maintain the Node-RED Pengines interface package. On the Pengines package I added both.

**Pull request merged**
